### ISSUE TITLE
Microsoft.NET.CoreFramework.Debug.2.2 required for 1.2.1.0

### ISSUE THREAD

**Issue by infeeeee** [youshengCode/IfcToolbox#10]
I could sideload 1.2.0.0, but I couldn't update/install 1.2.1.0 because of this missing dependency. 

What should I download or install? Is it intentional? 

Thanks for this tool, 1.2.0.0 works nicely!

**Comment by infeeeee** [comment]
I installed everything from the dependencies, x86 and x64, and still get the same error. It requests CoreFramework.Debug, but I can't see a file named similarly in your zip. 

// It's an office computer and I don't have permission to change update policies, but I can install anything on it.

**Comment by youshengCode** [comment]
Hi, could you tell me which version of OS you are using for your computer? 
// I think the CoreFramework stuff comes from the system itself. I will check it and let you know if I found something.

**Comment by infeeeee** [comment]
Windows 10 Pro, version 21H1 build 19043.1526

Windows Feature Experience Pack 120.2212.4170.0

Windows Update is up to date, this is the latest update installed on last week: https://support.microsoft.com/en-us/topic/february-8-2022-kb5010342-os-builds-19042-1526-19043-1526-and-19044-1526-bd5c4434-bec4-42e9-991d-5810d4ec52d9 

so it's not LTSC or something.
