### ISSUE TITLE
"An error in a system binary was detected. Try refreshing the pc to fix the problem"

### ISSUE THREAD

**Issue by francesco-gallo** [youshengCode/IfcToolbox#12]
Hello, I'm trying to IfcConvert to SVG some IFC models, but everytime I try the conversion I get a "An error in a system binary was detected. Try refreshing the pc to fix the problem" error message.  
I'm using the latest version from Windows Store.

I'm admin in my system, and there are no settings preventing background apps to run

Thanks

**Comment by youshengCode** [comment]
Hi @francesco-gallo, thanks for your feedback and sorry for the late reply. 
Actually, we have a discussion on the same issue #3 
Please try all those propositions first, and maybe give the sideload package a try.

I will mark this issue as duplication, if you still run into this error please add a new comment and reopen issue #3 
Thanks!
