### ISSUE TITLE
Can't delete ifc file on the applicaiton interface

### ISSUE THREAD

**Issue by CongzhengZOU** [youshengCode/IfcToolbox#13]
I have several ifc files, to find out which ifc need to relocate, I have to open them one by one. But nothing happened when I click delete icon. Is it because there is not yet operations behind this icon? 

![image](https://user-images.githubusercontent.com/70321029/173331050-3124a546-a763-401b-b896-b8e9d25d5b99.png)

**Comment by youshengCode** [comment]
Hi @CongzhengZOU, sorry for the late reply. 
I have tested the file import area. It seems correctly functional. 
Actually, it's the same component across diff tools in IFC Toolbox, if one is functional it will not have issues for others.

I will close this issue for now, please check if it happening again by restarting the application or your system. 
If you run into the same situation again, please provide more details like your environment and a scenario with detail, if possible, you could add a sample file too.

Thanks for your feedback.
