### ISSUE TITLE
Any plans to publish Tools and Core as NuGet

### ISSUE THREAD

**Issue by jsve** [youshengCode/IfcToolbox#9]
First of all - great project! I really like the application.

I have been looking at the code and it seems like you wrap the Xbim and IfcOpenShell in a neat way! Any plans to release this (guessing Tools and Core projects) as a NuGet?

**Comment by youshengCode** [comment]
Hey Johan, Thanks! 
Sure I have tried to wrap multiple libs together. For now, it works. But actually, I don't know if it's better for the long-term. 
The NuGet question is related to the licence of the original project. I think it's a NO under LGPL. 
And I would like to suggest you contribute directly to their repo or create new tools in this repo, in this way we can easily maintain and make it more stable : )
// So for now, you have to clone the Core and Tools projects and build your solution on your own.
